services:
  # --------------------------
  # Infrastructure Services
  # --------------------------
  postgres:
    image: postgres:15-alpine
    # restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    # restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}

  # --------------------------
  # Backend Microservices
  # --------------------------
  user-service:
    build:
      context: ../services/user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ../services/user-service:/usr/src/app
      - /usr/src/app/node_modules

  event-service:
    build:
      context: ../services/event-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ../services/event-service:/usr/src/app
      - /usr/src/app/node_modules

  club-service:
    build:
      context: ../services/club-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - KAFKA_BROKER=kafka:9092
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      zookeeper:
        condition: service_started
    command: sh -c "npx prisma migrate deploy && npm run dev"
    volumes:
      - ../services/club-service:/usr/src/app
      - /usr/src/app/node_modules

  notification-service:
    build:
      context: ../services/notification-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ../services/notification-service:/usr/src/app
      - /usr/src/app/node_modules

  # --------------------------
  # API Gateway
  # --------------------------
  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    ports:
      - "8088:8080"
    depends_on:
      - user-service
      - event-service
      - club-service
      - notification-service
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ../gateway:/usr/src/app
      - /usr/src/app/node_modules

  # --------------------------
  # Frontend (React via Vite)
  # --------------------------
  # frontend:
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   environment:
  #     - NODE_ENV=${NODE_ENV}
  #     - VITE_API_URL=${VITE_API_URL}

  frontend:
    build:
      context: ../frontend        # The folder containing your Dockerfile and app code
      dockerfile: Dockerfile       # Specify the Dockerfile (optional if it's named 'Dockerfile')
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development



  # --------------------------------
  # Nginx Reverse Proxy Configuration
  # --------------------------------
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8085:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - gateway
      - user-service
      - event-service
      - club-service
      - notification-service


volumes:
  pgdata:
  mongodata:
