name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # - name: Install Dependencies
      #   run: npm install

      - name: Build and Test with Docker Compose
        run: |
          docker compose -f config/docker-compose.yml up --build --abort-on-container-exit
          docker compose -f config/docker-compose.yml down
